#!/usr/bin/env bash
# Configure nginx to redirect to another page

sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
printf %s "server {
	listen 80 default_server;
	listen [::]: default_server;
	root /var/www/html;
	index index.html index.htm

	location /redirect_me {
		return 301 http://cuberulr.com/;
	}
}" > /etc/mginx/sites-available/default

sudo service nginx restart
