#!/usr/bin/env bash
# Configure nginx to redirect to another page

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
sudo service nginx restart
