#!/usr/bin/env bash
# Configure nginx to redirect to another page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World" > /etc/nginx/html/index.html
printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 http://cuberulr.com/;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
