#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains string Ceci n'est pas une page.

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World" > /var/www/html/index.html
echo "Ceci m'est pas une page" > /var/www/html/404.html

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 http://cuberulr.com/;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
