#!/usr/bin/env bash
# Configure web-02 to be identical to web-01
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root /var/www/html;

	location /redirect_me {
		return 301 http://cuberulr.com/;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
