#!/usr/bin/env bash
# Script that displays "Best School" 10 times
# but for the 9th iteration diusplays "Best School"
# then "Hi" on a new line

i=0
while [ $i -lt "10" ]
do
      echo "Best School"


      if [ $i -eq "9" ]
      then
             echo "Hi"
	     echo "Best School"
      fi

      ((i += 1))
done
